In [36]:
import numpy as np

In [37]:
M = np.array([[0,1],[2,3]])

In [38]:
M

array([[0, 1],
       [2, 3]])

In [39]:
M.reshape((4,1))

array([[0],
       [1],
       [2],
       [3]])

In [40]:
X_speedy_long = np.linspace(360-3.75,0,96)
Y_speedy_lat = np.array("-87.159 -83.479 -79.777 -76.070 -72.362 -68.652 -64.942 -61.232 -57.521 -53.810 -50.099 -46.389 -42.678 -38.967 -35.256 -31.545 -27.833 -24.122 -20.411 -16.700 -12.989 -9.278 -5.567 -1.856 1.856 5.567 9.278 12.989 16.700 20.411 24.122 27.833 31.545 35.256 38.967 42.678 46.389 50.099 53.810 57.521 61.232 64.942 68.652 72.362 76.070 79.777 83.479 87.159".split(" "))
Y_speedy_lat = Y_speedy_lat.astype(np.float32)

N_lon_speedy = X_speedy_long.size
N_lat_speedy = Y_speedy_lat.size

X_noaa_long = np.linspace(360-2.5,0,144)
Y_noaa_lat = np.linspace(-90,90,73)

N_lon_noaa = X_noaa_long.size
N_lat_noaa = Y_noaa_lat.size


obs_speedy = np.zeros((N_lon_speedy,N_lat_speedy));

obs_noaa = np.zeros((N_lon_noaa,N_lat_noaa));



In [41]:
obs_speedy.shape

(96, 48)

In [42]:
obs_noaa.shape

(144, 73)

In [43]:
obs_speedy = np.array([i for i in range(0,96*48)]);

In [44]:
obs_speedy

array([   0,    1,    2, ..., 4605, 4606, 4607])

In [45]:
obs_speedy = obs_speedy.reshape((96,48))

In [46]:
obs_noaa = np.array([i for i in range(0,144*73)])

In [47]:
obs_noaa = obs_noaa.reshape((144,73))

In [48]:
np.save('obs_noaa.npy',obs_noaa)

In [49]:
np.save('obs_speedy.npy',obs_noaa)

In [50]:
obs_new_noaa = np.load('obs_noaa.npy')

In [51]:
obs_new_noaa

array([[    0,     1,     2, ...,    70,    71,    72],
       [   73,    74,    75, ...,   143,   144,   145],
       [  146,   147,   148, ...,   216,   217,   218],
       ...,
       [10293, 10294, 10295, ..., 10363, 10364, 10365],
       [10366, 10367, 10368, ..., 10436, 10437, 10438],
       [10439, 10440, 10441, ..., 10509, 10510, 10511]])